version: '2.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      #- VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      #- VIRTUAL_HOST=proyecto2.cruizgo1.tk
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/archive/proyecto2.cruizgo1.tk:/etc/nginx/certs

  backend:
    image: backend
    build: .
    environment:
      - VIRTUAL_HOST=proyecto2.cruizgo1.tk
    restart: always
    ports:
      - 3000:3000
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb:/data/db
